version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: pridecontrol/robotframework-web:v1
        auth:
          username: $USERNAME
          password: $PASSWORD
    working_directory: /app/
    steps:
      - checkout
      - run:
          name: "Run Test"
          command: "robot -d ./reports/ -v HEADLESS:True ./tests/."
      - store_artifacts:
          path: /app/reports/

workflows:
  Web-Automation-Test-Workflow:
    jobs:
      - Build-and-Test
