version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: pridecontrol/robotframework-web:v1
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - run:
          name: "Preparing Testing"
          command: |
            cp ./resources/ /app/
            cp ./tests/ /app/
      - run:
          name: "Run Test"
          command: robot -d /app/reports/ -v HEADLESS:True /app/tests/.
      - store_artifacts:
          path: /app/reports/

workflows:
  Web-Automation-Test-Workflow:
    jobs:
      - Build-and-Test
