version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: pridecontrol/robotframework-web:v1
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            npm install dotenv run-func @penseapp/discord-notification
      - run:
          name: "Setup Environment Variable"
          command: |
            cd /app/
            echo "BUILD=$CIRCLE_BUILD_NUM" >> .env
            echo "REPOSITORY_URL=$CIRCLE_REPOSITORY_URL" >> .env
            echo "BUILD_URL=$CIRCLE_BUILD_URL" >> .env
            echo "BRANCH=$CIRCLE_BRANCH" >> .env
            echo "DISCORD_WEBHOOK=$DISCORD_WEBHOOK" >> .env
      - run:
          name: "Prepare Test"
          command: |
            mv -r ./resources/ /app/
            mv -r ./tests/ /app/
            mv ./discord-notification.js
            mkdir /app/reports/chromium
            mkdir /app/reports/firefox
            mkdir /app/reports/webkit
      - run:
          name: "Send Notification - Start Testing"
          command: npx run-func discord-notification.js test "start"
          when: always
      - run:
          name: "Run Test - Chromium"
          command: robot -d /app/reports/chromium/ -v HEADLESS:True /app/tests/.
      - run:
          name: "Run Test - Firefox"
          command: robot -d /app/reports/firefox/ -v HEADLESS:True -v BROWSER:firefox /app/tests/.
      - run:
          name: "Run Test - Webkit"
          command: robot -d /app/reports/webkit/ -v HEADLESS:True -v BROWSER:webkit /app/tests/.
      - run:
          name: "Send Notification - Stop Testing"
          command: npx run-func discord-notification.js test "stop"
          when: always
      - run:
          name: "Wrapping Test Results"
          command: tar -cvf artifact.tar /app/reports/
          when: always
      - store_artifacts:
          path: artifact.tar

workflows:
  Web-Automation-Test-Workflow:
    jobs:
      - Build-and-Test
